---
- hosts: dev
  become: True
  tasks:
    - name: start docker   
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module   
      pip:
        name: docker
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "devop/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          0.0.0.0:8088:8080
